source_dir="/Users/sam/.config/zsh"
plugin_dir="/Users/sam/.config/zsh/plugins"
source ${source_dir}/movement.sh
source ${source_dir}/setup.sh
source ${source_dir}/config_files.sh
source ${source_dir}/prompt.sh
source ${source_dir}/misc_alias.sh
# source ${source_dir}/nnn.sh

source ${plugin_dir}/zsh-git-support.sh
source ${plugin_dir}/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${plugin_dir}/zsh-vi-mode/zsh-vi-mode.zsh
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
source ${plugin_dir}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
